# Generated by Django 3.2.8 on 2026-01-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
    ]
